{% set version = "0.4.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-scorecard
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/scorecard_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/scorecard/scorecard_{{ version }}.tar.gz
  sha256: fb291c49453b64a101df79aadfd9c16682a6251e58663744ad74877623c4bd80

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cli
    - r-data.table >=1.10.0
    - r-doparallel
    - r-foreach
    - r-ggplot2
    - r-gridextra
    - r-openxlsx
    - r-stringi
    - r-xefun >=0.1.2
    - r-xml2
  run:
    - r-base
    - r-cli
    - r-data.table >=1.10.0
    - r-doparallel
    - r-foreach
    - r-ggplot2
    - r-gridextra
    - r-openxlsx
    - r-stringi
    - r-xefun >=0.1.2
    - r-xml2

test:
  commands:
    - $R -e "library('scorecard')"           # [not win]
    - "\"%R%\" -e \"library('scorecard')\""  # [win]

about:
  home: http://shichen.name/scorecard/
  dev_url: https://github.com/ShichenXie/scorecard
  doc_url: http://shichen.name/scorecard/reference/index.html
  license: MIT
  summary: 'The `scorecard` package makes the development of credit risk scorecard easier and efficient by providing functions for some common tasks, such as data partition, variable selection, woe binning, scorecard scaling, performance evaluation and report generation. These functions can also used in the development of
    machine learning models. The references including: 1. Refaat, M. (2011, ISBN: 9781447511199). Credit Risk Scorecard: Development and Implementation Using SAS. 2. Siddiqi, N. (2006, ISBN: 9780471754510). Credit risk scorecards. Developing and Implementing Intelligent Credit Scoring.'
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor
